### ISSUE TITLE
In cloud.Service, overloaded meaning of "image" is confusing

### ISSUE THREAD

**Issue by lindydonna** [pulumi/pulumi-cloud#217]
I was very confused when I saw this example:

```typescript
    containers: {
        nginx: {
            build: "./app",
            image: "pulumi/nginx",
            memory: 128,
            ports: [{ port: 80 }],
        },
    },
```

I assumed that it was overriding the contents of Dockerfile somehow, possibly composing with the image that was provided. Now that @lukehoban has explained how it works, I find the property `image` to be very misleading. The feature does seem useful, but can we rename to `image-name` instead?  

Plus, if you delete the line for `build`, now the program means something entirely different.

**Comment by lukehoban** [comment]
Closing this out as a one-off since it's not a big deal, we've shipped the API as is, and it's aligned with docker-compose.  We'll review APIs overall as part of https://github.com/pulumi/pulumi-cloud/issues/378 and may make changes overall in the `cloud.Service` API, but should look at that more holistically.
